# Generated by Django 2.2.13 on 2022-08-15 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='User_id',
            new_name='user_id',
        ),
    ]
