# Generated by Django 4.0.6 on 2022-07-18 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_rename_is_publised_listing_is_published'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='Address',
            new_name='address',
        ),
    ]
